### ISSUE TITLE
PRACTICA_PREDICADOS_EQUIPO_EDUARDO_TOMAS_FERIA_ORTIZ_1AS

### ISSUE THREAD

**Issue by Eduardo21620095** [SistemasTecTlaxiaco/practica-de-predicados-cuantificadores-team-eduardo-tomas-1as#1]
[PRÁCTRICA_PREDICADOS_1AS_EQUIPO_EDUARDO_TOMAS_FERIA_ORTIZ.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-predicados-cuantificadores-team-eduardo-tomas-1as/files/7502193/PRACTRICA_PREDICADOS_1AS_EQUIPO_EDUARDO_TOMAS_FERIA_ORTIZ.pdf)

**Comment by UrielGB10** [comment]
En esta práctica tiene la calificación de 25 en general esta bien,en la conclusión tiene detalles que se pueden mejorar para las siguientes prácticas.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
